import {
  LayoutDashboard,
  BookOpen,
  Sparkles,
  FileCheck,
  BarChart3,
  Settings,
  Users,
  GraduationCap,
  Network,
  Shield,
  ClipboardList,
  Library,
  Target,
  Layers,
  Building2,
  UserCog,
  Wand2,
  Bell,
  UserCircle,
  ListChecks,
  TrendingUp,
  AlertTriangle,
  FileText,
  CheckSquare,
  Database,
  HelpCircle,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  LayoutDashboard,
  BookOpen,
  Sparkles,
  FileCheck,
  BarChart3,
  Settings,
  Users,
  GraduationCap,
  Network,
  Shield,
  ClipboardList,
  Library,
  Target,
  Layers,
  Building2,
  UserCog,
  Wand2,
  Bell,
  UserCircle,
  ListChecks,
  TrendingUp,
  AlertTriangle,
  FileText,
  CheckSquare,
  Database,
  HelpCircle,
};

export function resolveIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? HelpCircle;
}
